# https://www.prisma.io/docs/1.32/get-started/01-setting-up-prisma-new-database-TYPESCRIPT-t002/#launch-prisma-and-the-connected-database

version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - d:\postgres:/var/lib/postgresql/data